// ─── Sample Resume Data ───────────────────────────────────────────────────────
// Two full personas ready to load for testing every section and template.

export const SAMPLE_RESUMES = [
  {
    key: 'software',
    label: 'Software Engineer',
    subtitle: 'Alex Rivera — Full-Stack Developer',
    emoji: '💻',
    color: '#14b8a6',
    data: {
      title: 'Alex Rivera — Software Engineer',
      template: 'modern',
      personal: {
        name: 'Alex Rivera',
        title: 'Senior Full-Stack Software Engineer',
        email: 'alex.rivera@email.com',
        phone: '+1 (415) 555-0192',
        location: 'San Francisco, CA',
        website: 'https://alexrivera.dev',
        linkedin: 'linkedin.com/in/alexrivera',
        summary:
          'Senior Full-Stack Engineer with 7+ years building scalable web applications and distributed systems. Passionate about clean architecture, developer experience, and mentoring junior engineers. Track record of reducing page load times by 60% and shipping features used by 5M+ users. Open-source contributor with 2,400+ GitHub stars.',
      },
      experience: [
        {
          id: 'exp-1',
          company: 'Stripe',
          position: 'Senior Software Engineer',
          location: 'San Francisco, CA',
          startDate: 'Mar 2021',
          endDate: '',
          current: true,
          description:
            'Lead engineer on the Payments Infrastructure team, responsible for the real-time transaction processing pipeline handling $1B+ daily volume.',
          bullets: [
            'Redesigned the payment retry logic, reducing failed transaction rate by 34% and recovering $12M in annual revenue.',
            'Built a distributed rate-limiter in Go that processes 400K req/s with sub-millisecond latency at p99.',
            'Led migration of 6 legacy Ruby services to a TypeScript/Node.js microservice architecture, cutting mean deploy time from 45 min to 4 min.',
            'Mentored 4 junior engineers and conducted 50+ technical interviews; improved team hiring pass rate by 20%.',
          ],
        },
        {
          id: 'exp-2',
          company: 'Airbnb',
          position: 'Software Engineer II',
          location: 'San Francisco, CA',
          startDate: 'Jun 2018',
          endDate: 'Feb 2021',
          current: false,
          description:
            'Full-stack engineer on the Search & Discovery team, owning the search ranking algorithm and front-end results page.',
          bullets: [
            'Re-architected the search results React app with code-splitting and lazy loading, improving Core Web Vitals score from 43 to 91.',
            'Built a real-time pricing experimentation framework (A/B testing) serving 200M+ queries/day, directly contributing to a 7% booking rate lift.',
            'Implemented server-side rendering with Next.js, reducing Time-to-First-Byte by 58%.',
          ],
        },
        {
          id: 'exp-3',
          company: 'Pivotal Labs',
          position: 'Software Engineer',
          location: 'New York, NY',
          startDate: 'Aug 2016',
          endDate: 'May 2018',
          current: false,
          description:
            'Consulting engineer embedded with client teams to deliver greenfield applications and modernize legacy codebases.',
          bullets: [
            'Delivered 8 client projects end-to-end using React, Ruby on Rails, and PostgreSQL within tight 3-month sprints.',
            'Introduced TDD practices across three client teams, increasing test coverage from <20% to >85%.',
          ],
        },
      ],
      education: [
        {
          id: 'edu-1',
          school: 'Carnegie Mellon University',
          degree: 'Bachelor of Science',
          field: 'Computer Science',
          startDate: 'Aug 2012',
          endDate: 'May 2016',
          gpa: '3.82',
          description: 'Focus on Distributed Systems & Programming Languages. Dean\'s List all 8 semesters. President of ACM student chapter.',
        },
      ],
      skills: [
        { id: 's1', name: 'TypeScript' },
        { id: 's2', name: 'React' },
        { id: 's3', name: 'Node.js' },
        { id: 's4', name: 'Go' },
        { id: 's5', name: 'Python' },
        { id: 's6', name: 'PostgreSQL' },
        { id: 's7', name: 'Redis' },
        { id: 's8', name: 'Kafka' },
        { id: 's9', name: 'Docker' },
        { id: 's10', name: 'Kubernetes' },
        { id: 's11', name: 'AWS' },
        { id: 's12', name: 'GraphQL' },
        { id: 's13', name: 'Next.js' },
        { id: 's14', name: 'Terraform' },
        { id: 's15', name: 'CI/CD' },
      ],
      projects: [
        {
          id: 'p1',
          name: 'OpenRPC — API Schema Toolkit',
          description:
            'Open-source library for auto-generating type-safe API clients from JSON-RPC schemas. 2,400+ GitHub stars, 180K weekly npm downloads. Used by 300+ companies including Cloudflare and Figma.',
          url: 'https://github.com/alexrivera/openrpc',
          technologies: 'TypeScript, Node.js, JSON Schema, GitHub Actions',
          startDate: 'Jan 2020',
          endDate: '',
        },
        {
          id: 'p2',
          name: 'Latency Dashboard',
          description:
            'Real-time observability dashboard for distributed systems latency analysis. Features p50/p95/p99 percentile tracking, flame graphs, and Slack alerting. Built during a 48-hour internal hackathon; now used by 12 engineering teams at Stripe.',
          url: 'https://github.com/alexrivera/latency-dash',
          technologies: 'React, D3.js, WebSockets, ClickHouse',
          startDate: 'Nov 2022',
          endDate: 'Dec 2022',
        },
        {
          id: 'p3',
          name: 'devenv-cli',
          description:
            'CLI tool that spins up reproducible local dev environments in <30 seconds using Docker Compose. 800+ GitHub stars.',
          url: 'https://github.com/alexrivera/devenv-cli',
          technologies: 'Go, Docker, YAML, Cobra CLI',
          startDate: 'Mar 2023',
          endDate: '',
        },
      ],
      certifications: [
        {
          id: 'c1',
          name: 'AWS Certified Solutions Architect – Professional',
          issuer: 'Amazon Web Services',
          date: 'Sep 2022',
          url: 'https://aws.amazon.com/certification',
        },
        {
          id: 'c2',
          name: 'Certified Kubernetes Administrator (CKA)',
          issuer: 'Cloud Native Computing Foundation',
          date: 'Mar 2021',
          url: 'https://www.cncf.io/certification/cka/',
        },
        {
          id: 'c3',
          name: 'Google Cloud Professional Data Engineer',
          issuer: 'Google Cloud',
          date: 'Jul 2023',
          url: 'https://cloud.google.com/certification',
        },
      ],
    },
  },

  {
    key: 'marketing',
    label: 'Marketing Manager',
    subtitle: 'Jordan Chen — Growth & Brand Strategist',
    emoji: '📊',
    color: '#f97316',
    data: {
      title: 'Jordan Chen — Marketing Manager',
      template: 'classic',
      personal: {
        name: 'Jordan Chen',
        title: 'Senior Marketing Manager — Growth & Brand Strategy',
        email: 'jordan.chen@email.com',
        phone: '+1 (312) 555-0874',
        location: 'Chicago, IL',
        website: 'https://jordanchen.co',
        linkedin: 'linkedin.com/in/jordanchen',
        summary:
          'Results-driven marketing leader with 8 years of experience scaling consumer brands from $10M to $200M ARR. Expert in data-driven growth strategies, multi-channel campaigns, and building high-performance marketing teams. Proven ability to reduce CAC by 40% while growing LTV through lifecycle marketing and community-led growth.',
      },
      experience: [
        {
          id: 'exp-1',
          company: 'Notion',
          position: 'Senior Marketing Manager',
          location: 'Remote (Chicago, IL)',
          startDate: 'Jan 2022',
          endDate: '',
          current: true,
          description:
            'Own the B2C growth and brand marketing function, managing a $4M annual budget and a team of 6 marketers.',
          bullets: [
            'Grew free-to-paid conversion rate from 8% to 14% through a redesigned onboarding email sequence and in-app nudge strategy.',
            'Launched the "Build with Notion" creator program, signing 120 template creators who collectively drove 380K new signups in 6 months.',
            'Owned SEO strategy that grew organic traffic from 1.2M to 4.8M monthly visitors; now the top acquisition channel at 52% of all signups.',
            'Executed a product-led growth rebrand campaign reaching 28M impressions across LinkedIn, Twitter, and YouTube.',
          ],
        },
        {
          id: 'exp-2',
          company: 'Duolingo',
          position: 'Marketing Manager',
          location: 'Pittsburgh, PA',
          startDate: 'Mar 2019',
          endDate: 'Dec 2021',
          current: false,
          description:
            'Led performance and lifecycle marketing for North America and LATAM markets.',
          bullets: [
            'Reduced customer acquisition cost by 41% through rigorous paid social A/B testing across Facebook, TikTok, and Snapchat.',
            'Built and launched the streak-recovery push notification system, recovering 2.3M lapsed users per month.',
            'Managed influencer partnerships with 45 creators (cumulative 18M followers), generating $1.2M in tracked attributable installs.',
            'Coordinated the "Duo is Dead" viral campaign that earned 620M earned media impressions and 98K app store reviews in 72 hours.',
          ],
        },
        {
          id: 'exp-3',
          company: 'HubSpot',
          position: 'Content Marketing Specialist',
          location: 'Boston, MA',
          startDate: 'Jul 2016',
          endDate: 'Feb 2019',
          current: false,
          description:
            'Created and distributed long-form content and lead magnets for the SMB marketing persona.',
          bullets: [
            'Produced 80+ blog posts that collectively rank for 14,000 keywords and drive 650K monthly organic visits.',
            'Developed 12 downloadable templates and guides generating 95K marketing-qualified leads annually.',
          ],
        },
      ],
      education: [
        {
          id: 'edu-1',
          school: 'Northwestern University — Kellogg School of Management',
          degree: 'Master of Business Administration',
          field: 'Marketing & Strategy',
          startDate: 'Sep 2014',
          endDate: 'Jun 2016',
          gpa: '3.76',
          description: 'Marketing Club President. Case competition finalist (Kellogg Marketing Summit). Full Merit Scholarship recipient.',
        },
        {
          id: 'edu-2',
          school: 'University of Illinois Urbana-Champaign',
          degree: 'Bachelor of Science',
          field: 'Communications & Psychology',
          startDate: 'Aug 2010',
          endDate: 'May 2014',
          gpa: '3.91',
          description: 'Summa Cum Laude. Editor-in-Chief of the student newspaper. Interned at Leo Burnett advertising agency junior year.',
        },
      ],
      skills: [
        { id: 's1', name: 'Growth Marketing' },
        { id: 's2', name: 'SEO / SEM' },
        { id: 's3', name: 'Content Strategy' },
        { id: 's4', name: 'Email Marketing' },
        { id: 's5', name: 'Performance Ads' },
        { id: 's6', name: 'Brand Strategy' },
        { id: 's7', name: 'Google Analytics 4' },
        { id: 's8', name: 'HubSpot CRM' },
        { id: 's9', name: 'Salesforce' },
        { id: 's10', name: 'Figma' },
        { id: 's11', name: 'SQL' },
        { id: 's12', name: 'A/B Testing' },
        { id: 's13', name: 'Lifecycle Marketing' },
        { id: 's14', name: 'Influencer Partnerships' },
        { id: 's15', name: 'Product-Led Growth' },
      ],
      projects: [
        {
          id: 'p1',
          name: 'The Retention Playbook (Newsletter)',
          description:
            'Weekly newsletter on SaaS retention and lifecycle marketing strategies. 22,000 subscribers, 48% average open rate. Featured in Marketing Brew and Growth.Design.',
          url: 'https://retentionplaybook.substack.com',
          technologies: 'Substack, Beehiiv, ConvertKit',
          startDate: 'Feb 2021',
          endDate: '',
        },
        {
          id: 'p2',
          name: '"Brand Voice at Scale" Workshop',
          description:
            'Developed and facilitates a half-day workshop teaching marketing teams how to scale content creation without losing brand voice. Delivered to 14 companies including Canva and Figma. 98% satisfaction score.',
          url: '',
          technologies: 'Workshop Facilitation, Notion, Miro',
          startDate: 'Jun 2022',
          endDate: '',
        },
        {
          id: 'p3',
          name: 'CAC Benchmarking Tool',
          description:
            'Spreadsheet model that benchmarks CAC, LTV, and payback period across 7 acquisition channels. Downloaded 4,200+ times from Product Hunt (#3 Product of the Day).',
          url: 'https://producthunt.com/posts/cac-benchmark',
          technologies: 'Google Sheets, Data Studio',
          startDate: 'Nov 2022',
          endDate: 'Nov 2022',
        },
      ],
      certifications: [
        {
          id: 'c1',
          name: 'Google Analytics 4 Certification',
          issuer: 'Google',
          date: 'Jan 2023',
          url: 'https://skillshop.google.com',
        },
        {
          id: 'c2',
          name: 'Meta Blueprint — Advanced Media Buying',
          issuer: 'Meta',
          date: 'Aug 2022',
          url: 'https://www.facebook.com/business/learn',
        },
        {
          id: 'c3',
          name: 'HubSpot Content Marketing Certification',
          issuer: 'HubSpot Academy',
          date: 'Mar 2021',
          url: 'https://academy.hubspot.com',
        },
        {
          id: 'c4',
          name: 'CXL Institute — Growth Marketing Minidegree',
          issuer: 'CXL Institute',
          date: 'Oct 2020',
          url: 'https://cxl.com/institute',
        },
      ],
    },
  },

  {
    key: 'designer',
    label: 'UX Designer',
    subtitle: 'Sam Okafor — Product Design Lead',
    emoji: '🎨',
    color: '#a855f7',
    data: {
      title: 'Sam Okafor — UX / Product Designer',
      template: 'minimal',
      personal: {
        name: 'Sam Okafor',
        title: 'Senior Product Designer — UX & Design Systems',
        email: 'sam.okafor@design.io',
        phone: '+1 (646) 555-0331',
        location: 'Brooklyn, NY',
        website: 'https://samokafor.design',
        linkedin: 'linkedin.com/in/samokafor',
        summary:
          'Senior Product Designer with 6 years crafting high-impact digital experiences at the intersection of research, interaction design, and design systems. Led end-to-end design for products used by 3M+ people. Advocate for accessibility-first design — every project I ship meets WCAG 2.1 AA standards. Previously at Google and Figma.',
      },
      experience: [
        {
          id: 'exp-1',
          company: 'Linear',
          position: 'Senior Product Designer',
          location: 'Remote (New York, NY)',
          startDate: 'Feb 2022',
          endDate: '',
          current: true,
          description:
            'Own design for the core issue tracking and project management surfaces, serving 40,000+ engineering teams worldwide.',
          bullets: [
            'Redesigned the issue creation flow, reducing median creation time from 42s to 11s (74% faster) — highest-rated feature in the 2023 user survey.',
            'Built and maintain Linear\'s design system (Cosmos), a 380-component Figma library used by all 5 designers and referenced in engineering specs.',
            'Led a 0→1 design of the Cycles (sprint planning) feature, shipped in Q1 2023 and adopted by 62% of teams within 60 days.',
            'Established a biweekly user research cadence, conducting 8–10 moderated sessions per quarter with 150+ participant network.',
          ],
        },
        {
          id: 'exp-2',
          company: 'Figma',
          position: 'Product Designer',
          location: 'San Francisco, CA',
          startDate: 'Jun 2019',
          endDate: 'Jan 2022',
          current: false,
          description:
            'Designer on the Editor Platform team, responsible for the canvas, selection, and component systems.',
          bullets: [
            'Designed the Auto Layout v3 feature (flexbox-based) — rated the #1 most impactful Figma feature in the 2021 Config survey with 89% satisfaction.',
            'Partnered with the accessibility team to audit and fix 130 color contrast and keyboard navigation issues across Figma\'s core UI.',
            'Created onboarding flows for new users that improved 7-day activation rate by 22%.',
          ],
        },
        {
          id: 'exp-3',
          company: 'Google',
          position: 'UX Designer (Contract)',
          location: 'New York, NY',
          startDate: 'Sep 2017',
          endDate: 'May 2019',
          current: false,
          description:
            'Embedded UX designer on the Google Maps Local Guides program.',
          bullets: [
            'Designed the photo contribution and review flows for 100M+ Local Guides, localised for 40 markets.',
            'Ran 12 usability studies with participants across the US, India, and Brazil to surface cross-cultural UX patterns.',
          ],
        },
      ],
      education: [
        {
          id: 'edu-1',
          school: 'Rhode Island School of Design (RISD)',
          degree: 'Bachelor of Fine Arts',
          field: 'Graphic Design',
          startDate: 'Sep 2013',
          endDate: 'May 2017',
          gpa: '3.88',
          description: 'Graduated with Distinction. Senior thesis: "Invisible Design — accessibility as a creative constraint." Recipient of the AIGA Student Design Award.',
        },
      ],
      skills: [
        { id: 's1', name: 'Figma' },
        { id: 's2', name: 'Prototyping' },
        { id: 's3', name: 'Design Systems' },
        { id: 's4', name: 'User Research' },
        { id: 's5', name: 'Usability Testing' },
        { id: 's6', name: 'Information Architecture' },
        { id: 's7', name: 'Accessibility (WCAG)' },
        { id: 's8', name: 'Motion Design' },
        { id: 's9', name: 'HTML & CSS' },
        { id: 's10', name: 'React (basics)' },
        { id: 's11', name: 'Framer' },
        { id: 's12', name: 'Storybook' },
        { id: 's13', name: 'Miro' },
        { id: 's14', name: 'Lottie / After Effects' },
      ],
      projects: [
        {
          id: 'p1',
          name: 'Cosmos Design System',
          description:
            'Comprehensive design system for Linear covering typography, color tokens, spacing, 380+ components, and interaction patterns. Documented in Figma and Storybook, consumed by 5 designers and 35 engineers. Reduced design-to-dev handoff time by 50%.',
          url: 'https://linear.app/design',
          technologies: 'Figma, Storybook, Tokens Studio, React',
          startDate: 'Apr 2022',
          endDate: '',
        },
        {
          id: 'p2',
          name: 'AccessScan — Chrome Extension',
          description:
            'Free Chrome extension that scans any webpage for WCAG 2.1 AA violations and generates a prioritised fix report. 12,000+ active users, 4.7/5 stars on Chrome Web Store.',
          url: 'https://chrome.google.com/store/accessscan',
          technologies: 'Figma, HTML/CSS, JavaScript, axe-core',
          startDate: 'Jan 2021',
          endDate: 'Apr 2021',
        },
        {
          id: 'p3',
          name: '"Designing for Everyone" Case Study Series',
          description:
            'Written series of 8 long-form case studies exploring inclusive design decisions. 85K total reads on Medium, republished in UX Collective and Smashing Magazine.',
          url: 'https://medium.com/@samokafor',
          technologies: 'Medium, Figma (diagrams), Notion',
          startDate: 'Mar 2020',
          endDate: '',
        },
      ],
      certifications: [
        {
          id: 'c1',
          name: 'Nielsen Norman Group UX Certification',
          issuer: 'Nielsen Norman Group',
          date: 'Nov 2021',
          url: 'https://www.nngroup.com/ux-certification/',
        },
        {
          id: 'c2',
          name: 'Interaction Design Foundation — UX Management',
          issuer: 'Interaction Design Foundation',
          date: 'May 2020',
          url: 'https://www.interaction-design.org',
        },
        {
          id: 'c3',
          name: 'CPACC — Certified Professional in Accessibility Core Competencies',
          issuer: 'IAAP',
          date: 'Feb 2022',
          url: 'https://www.accessibilityassociation.org',
        },
      ],
    },
  },
]
